// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2WvUxvcMIHB7eCm-HjbcDISd6P_eWGLs',
    appId: '1:599744497325:web:8bab3dfd93dc7090f92824',
    messagingSenderId: '599744497325',
    projectId: 'my-chat-app-bea0b',
    authDomain: 'my-chat-app-bea0b.firebaseapp.com',
    storageBucket: 'my-chat-app-bea0b.appspot.com',
    measurementId: 'G-TYEW1E081E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOij2wzO9OzgUYNJuUNhuTWfBe0r0TarU',
    appId: '1:599744497325:android:7a90947c0ad21bf1f92824',
    messagingSenderId: '599744497325',
    projectId: 'my-chat-app-bea0b',
    storageBucket: 'my-chat-app-bea0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF-y0yQogR611E5P-6lOmmS8W-ip9lepk',
    appId: '1:599744497325:ios:4ac98058b866b9a2f92824',
    messagingSenderId: '599744497325',
    projectId: 'my-chat-app-bea0b',
    storageBucket: 'my-chat-app-bea0b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF-y0yQogR611E5P-6lOmmS8W-ip9lepk',
    appId: '1:599744497325:ios:edd19a6a30586fbbf92824',
    messagingSenderId: '599744497325',
    projectId: 'my-chat-app-bea0b',
    storageBucket: 'my-chat-app-bea0b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
